testserver :
	# g++ -o testserver testserver.cc -lmynetlib -lpthread -std=c++17 -g
	g++ -o mynetlib_echo mynetlib_echo.cc -lmynetlib -lpthread -std=c++17 -g

clean :
	rm -f testserver
	rm -f mynetlib_echo